### ISSUE TITLE
FEAT: dream_web - allow configuring output path, samplers

### ISSUE THREAD

**Issue by tildebyte** [lstein/stable-diffusion#115]
I took a poke at it myself, but the way it's currently structured has a chicken-egg problem:

- T2I is instantiated without options, and *adding* options at that point would be difficult
- These two options are **only** available at instantiation time (i.e. *currently* can't be added to the `txt2img` call)

I reckon it's going to require a teensy bit of refactoring

**Comment by lstein** [comment]
The output_dir restriction is just me being lazy. The directory can be changed at any time, and in fact the poorly documented "cd" command does it at the dream> line.

With respect to the samplers, the original code was a rat's nest and I had thought that the model depended on the sampler rather than the other way around. Now that it's only a mouse's nest, I just need to move a bit of code in load_model() into its own method and we'll have the functionality.

So thanks for posting the nudge. It's on my personal TODO, and will probably get done over the next couple days.
