### ISSUE TITLE
Dream.py fails after "initializing...." with no output

### ISSUE THREAD

**Issue by BunnCode** [lstein/stable-diffusion#172]
I wish I could give more information with this report, but unfortunately there is simply no output at all.
After following all install steps and running dream.py, I get the following output 

![image](https://user-images.githubusercontent.com/17638042/187101877-ed2d64ea-1077-4cb6-9714-10f94c770594.png)

I have pre-loaded the model, correctly linked the weights, etc. Unfortunately there is no debug output whatsoever so I am not sure what is going wrong.

I am running on Ubuntu 20.04.1 LTS via WSL and have the latest version of Anaconda and Python.

**Comment by blessedcoolant** [comment]
Hard to troubleshoot without more info but what happens after this right away is the loading of the model and creation of the output folder.

Odd shots but let's try some solutions. Are you sure that your terminal has permissions to create new folders?

**Comment by BunnCode** [comment]
Yep, it definitely should; mkdir works. I added some debug lines to dream.py, and I was able to isolate the crash to this line;

 t2i.load_model()

after hitting this line, the script halts immediately.

**Comment by blessedcoolant** [comment]
> Yep, it definitely should; mkdir works. I added some debug lines to dream.py, and I was able to isolate the crash to this line;
> 
> t2i.load_model()
> 
> after hitting this line, the script halts immediately.

Is the model in the correct place? models/ldm/stable-diffusion-v1/model.ckpt  ....?

**Comment by BunnCode** [comment]
Yep! 
![image](https://user-images.githubusercontent.com/17638042/187118211-7f0d7d1c-4f1a-4a1f-a0ba-c858a8d19efa.png)
or rather a symlink is there. I am pretty sure that I followed all the installation steps correctly, I'm not sure what could be causing it.

**Comment by blessedcoolant** [comment]
> Yep! ![image](https://user-images.githubusercontent.com/17638042/187118211-7f0d7d1c-4f1a-4a1f-a0ba-c858a8d19efa.png) or rather a symlink is there. I am pretty sure that I followed all the installation steps correctly, I'm not sure what could be causing it.

Does your graphic card support CUDA?

**Comment by lstein** [comment]
I encountered exactly the same problem last night and realized that it was happening because I was running on a system with a non-supported graphics card. It turns out that I was too aggressive in quieting torch messages. Please do a pull from "main", which adds more verbose error reporting when the model fails to initialize, and post the trace back here. Hopefully this will give us a lead to work with.

**Comment by lstein** [comment]
Any luck?

**Comment by BunnCode** [comment]
> 

Apologies for the slow response; Unfortunately, no, but I think this might be related to WSL driver weirdness, since my card is a 2070 that I've executed CUDA jobs on pretty frequently before. I'm going to try some possible fixes but worst case I might just default to running it on windows.

**Comment by tildebyte** [comment]
It actually works *really* well on "native" Windows.

@BunnCode; If you wouldn't mind, could I trouble you to run through https://github.com/lstein/stable-diffusion/wiki/Easy-peasy-Windows-install and see how it goes? The instructions there might be over-simplified for you, given that I see that you're using WSL in a pretty sophisticated way, but I'd actually like to have some feedback from someone who's pretty familiar with these tools.

**Comment by lstein** [comment]
@tildebyte Just now saw your Windows install guide. Thank you! I wonder if this should supersede the instructions in the README?

**Comment by lstein** [comment]
@BunnCode If you don't mind doing a little testing, I'll create a branch for you that has print statements scattered around the model loading code so that we have an idea where it is crapping out. I'll send you the branch name tomorrow when it's ready.

**Comment by tildebyte** [comment]
@lstein; I’d like a few more “test drivers”, but I find that, at least on Windows, it’s a much easier install (and *faster* - why is Conda sooo slow? it even uses `pip` behind the scenes…), with fewer moving parts, and is slightly less complicated than Conda (and I vastly prefer `pew`). Also, as we saw a few days ago, there are situations where conda fails to inform the user about what’s going on behind the scenes and simply sits there (that’s what prompted me to try a “pure pip” install in the first place). 

One thing of note: I’ve been using Python 3.10 without issue since the weekend after noticing it in upstream’s deps. 

The only issues I ran into were

- “pytorch” isn’t a package on PyPi at all - I don’t understand what Conda is doing there
- I had to find updated binary wheels for torch and numpy - not a big deal
- “transformers” causes a traceback, “taming-transformers-rom1504” does not - this applies to Py 3.8 as well

**Comment by BunnCode** [comment]
> @BunnCode If you don't mind doing a little testing, I'll create a branch for you that has print statements scattered around the model loading code so that we have an idea where it is crapping out. I'll send you the branch name tomorrow when it's ready.

Very sorry for the slow response! Life got ahead of me. Sure, I can absolutely do that- I was ultimately able to get the project working on windows but it would be cool for it to work in WSL as well.

**Comment by BunnCode** [comment]
> It actually works _really_ well on "native" Windows.
> 
> @BunnCode; If you wouldn't mind, could I trouble you to run through https://github.com/lstein/stable-diffusion/wiki/Easy-peasy-Windows-install and see how it goes? The instructions there might be over-simplified for you, given that I see that you're using WSL in a pretty sophisticated way, but I'd actually like to have some feedback from someone who's pretty familiar with these tools.

Thanks for this- I actually had an extreme amount of difficulty getting conda to work on windows (which is actually why I was using WSL in the first place), although that isn't the fault of the maintainers of this repo. For some reason, the newer versions of conda and miniconda weren't capable of properly initializing in any of the shortcut shells, but I was able to get it working by downloading a version released in 2019 and then upgrading it via the shell. 

Your guide would have been absolutely indispensable if I wasn't able to get conda functioning, so thanks for that! If you would like, I can try setting up the project with pew instead of conda and tell you how it goes.
