### ISSUE TITLE
dream_log.txt is not updated and metadata is not written inside PNG files if CTRL+C is pressed

### ISSUE THREAD

**Issue by morganavr** [lstein/stable-diffusion#21]
I set -n to 100 and then pressed CTRL+C and *interrupted* message appeared. 
Then I opened dream_log.txt to view seeds for newly generated images but there was no info about them.
What is worse - newly generated images did not have EXIF metadata so there was no way to know their Seed values to recreate them later with different parameters.

**Comment by KnobleSavage** [comment]
I too was unable to locate any of the prompting info in the meta data using Gimp.

**Comment by morganavr** [comment]
This code will modify text2image function to write Seed string inside image files immediately
![image](https://user-images.githubusercontent.com/51041813/186047744-b6001966-971f-432a-bc6f-486c628f5c94.png)

**Comment by KnobleSavage** [comment]
Traceback (most recent call last):
  File "scripts/dream.py", line 332, in <module>
    main()
  File "scripts/dream.py", line 78, in main
    main_loop(t2i,cmd_parser,log)
  File "scripts/dream.py", line 133, in main_loop
    results = t2i.txt2img(**vars(opt))
  File "c:\sd\stable-diffusion\ldm\simplet2i.py", line 223, in txt2img
    info = PngImagePlugin.PngInfo()
NameError: name 'PngImagePlugin' is not defined

Perhaps you have an IDE that's pulling in imports automatically or some such?

In any case, I can wait for you guys do get this coded, since, really, we will want more than just the seed anyway.  The idea is that the meta-data will include everything we'll need to recreate the image.  (prompt, steps, height, width... seed etc. ) (This is a "nice-to-have").

Thanks,
KS

**Comment by lstein** [comment]
Ok, I can fix that by changing where the try: block is. Will be in version 1.06

**Comment by lstein** [comment]
Metadata is now rewritten to the log and PNG files when a series of generations is interrupted by ^C.

Some image programs can display the prompt metadata and others can't. Try Imagemagick on Linux, or use the "identify -verbose <filename>" command line. I have also provided a script called images2prompt.py that will retrieve the prompt metadata from a series of files from the command line.

**Comment by morganavr** [comment]
There is still a problem with writing metadata to PNG files only at the end of bulk generation (or after CTRL+C) - it's an unexpected crash of the script or when PC turns off suddenly (electricity off). Imagine you were running script for 10,000 images and 23 hours later electricity went off and all images that were generated will not have metadata (most importantly seed).

That's why I propose to write at least "seed" information to the images during initial save.
