### ISSUE TITLE
Feature Request: Clear init_img in WebUI

### ISSUE THREAD

**Issue by lstein** [lstein/stable-diffusion#212]
After you provide an init_img to the dream WebUI the uploaded file is sticky and continues to be used for subsequent generations. There's no obvious UI element to clear it (but it can be done by opening the file select dialog and then cancelling). Can a suitable UI element be added? @bakkot @TesseractCat

**Comment by arothmanmusic** [comment]
I've simply been reloading the page to clear the image. If there's going to be a manual 'clear' option (which there should be) then reloading the page ought to remember the file so you don't have to re-browse for it.

**Comment by namion** [comment]
Yes, I agree, this would be a convenient addition.

And I don't mean to hijack, but while we are on the topic of adding UI elements for the img2img portion of the WebUI, can you please consider adding a field for the --strength parameter? As mentioned in #134 and #202. I feel it is critical for img2img and as such, I have not been using the img2img feature of the WebUI because of it

**Comment by bakkot** [comment]
As an alternative, we could consider splitting up the interface so there's different tabs for txt2img vs img2img. There's a few fields which are only relevant to each - width/height only make sense for txt2img, and init-img/strength only make sense for img2img. Also, that way if we add any further modes (here I am thinking of [generating variants](https://github.com/lstein/stable-diffusion/pull/184) and interpolation) those features could go in their own tabs, instead of cluttering up the main interface with mutually-incompatible sets of UI elements.

Thoughts?

**Comment by arothmanmusic** [comment]
I think the most elegant solution would be to add/show the additional relevant fields when an image has been selected, and then remove/hide them again if the proposed 'clear' button for the img has been clicked.

**Comment by lstein** [comment]
Fix is in current development branch. Will go to release real soon.
