### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED - SOLVED: Update your GPU

### ISSUE THREAD

**Issue by Dartterious** [lstein/stable-diffusion#25]
Receiving the below error after trying to load this onto my beefier PC. 

Thanks in advance for any help! 
![image](https://user-images.githubusercontent.com/109719059/186072373-f1be2b14-9a72-4c60-8b0b-47c8efbaba01.png)

**Comment by lstein** [comment]
I've never seen this, but Googling suggests that it is caused by an outdated GPU driver. Here's instructions for fixing the problem from StackOverflow: https://stackoverflow.com/questions/60413943/cudnn-status-not-initialized-why-is-tensorflow-in-python-pycharm-so-finicky

Let me know what you find out.

**Comment by Dartterious** [comment]
That was it! Thank you!
