### ISSUE TITLE
img2img results compared to CompVis repo

### ISSUE THREAD

**Issue by mcuca1** [lstein/stable-diffusion#378]
Hi, I'm unable to reproduce the quality of the img2img example in the original stable-diffusion repository:

https://github.com/CompVis/stable-diffusion

with prompt:

python scripts/img2img.py --prompt "A fantasy landscape, trending on artstation" --init-img <path-to-img.jpg> --strength 0.8

Inputting their same input image. I've tried various settings but nothing seems to come close.

Is this normal or there is something I need to change?

Set up is as detailed here: https://medium.com/geekculture/run-stable-diffusion-in-your-local-computer-heres-a-step-by-step-guide-af128397d424

Thanks in advance

**Comment by lstein** [comment]
I would be happy to investigate. Where can I download the jpg image that you have been testing with?

**Comment by mcuca1** [comment]
Hi, I'm not using the -l switch, the picture is the exampel from the CompVis repo readme,

https://github.com/CompVis/stable-diffusion/raw/main/assets/stable-samples/img2img/sketch-mountains-input.jpg

the model I'm using is stable-diffusion-v-1-4-original

Am I using the wrong model?

Thanks

**Comment by Bendito999** [comment]
Are you specifying the same Seed on both? Probably should to properly compare them.

**Comment by mcuca1** [comment]
No because the seed was not shared in the example, but I can share some of my results and you will see that there is no way you will ever get something that compares, with th same input. Clearly something is wrong. You can easily test and see the results are just poor.

**Comment by mcuca1** [comment]
I see, apologies for the confusion, it's because I am using the web interface, anyway yes I am using img2img providing the same sketch as input

**Comment by lstein** [comment]
Sorry it took me so long to get back to you. I used the dream.py script rather than img2img and gave it this command:
~~~
dream> a fantasy landscape, trending on artstation -I./test-pictures/sketch-mountains-input.jpg
~~~
This yielded the following:
![000018 4154063514](https://user-images.githubusercontent.com/111189/189263675-74fba31c-83c5-4ed3-abcf-35517bdcbe2b.png)

I agree that this is not as good as the example on the CompViz page, so I upped the steps to 100, increased the CFG to 15, and asked for three more images:

~~~
dream> a fantasy landscape, trending on artstation -I./test-pictures/sketch-mountains-input.jpg -s100 -C15 -n3
~~~

This gave me the series of images shown below, which I think are comparable in quality to the CompViz example.
![000019 589655830](https://user-images.githubusercontent.com/111189/189263944-4ad6766e-a351-4851-96ff-4a7300637836.png)


![000020 527479233](https://user-images.githubusercontent.com/111189/189263948-9d38d2e6-ef11-4ca9-9eb7-0ab831e399ed.png)


![000020 1154247043](https://user-images.githubusercontent.com/111189/189263952-842bad55-63dc-406f-91f2-2bea0afe6736.png)

Do you agree, or is there still a quality gap?
