### ISSUE TITLE
The latest commit seems to create an issue with textual inversion

### ISSUE THREAD

**Issue by thelamedia** [lstein/stable-diffusion#508]
I had been using an old commit, but after pulling today I get the following error when trying to run training: 

`
File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 4096, 320]], which is output 0 of AsStridedBackward0, is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
`

Any ideas?

**Comment by lstein** [comment]
This is very strange. The error message only refers to torch packages and there's no reference to code in this package. Did you do anything else, such as update the torch library? Did you pull from development or from somewhere else?

If the problem is persistent, could you try checking out older commits to see if you can roughly identify which commit introduced the problem?

**Comment by thelamedia** [comment]
It is super odd.  I'm using the exact same packages on install (running in a docker env) and installing the same versions each time.  I rolled back to a commit that I zipped on the 3rd which works perfectly.  Today, I did a pull so something between then and now went wonky somewhere.  If I get time tomorrow I will try a few different commits along that path to see if I can narrow down a commit for you where it breaks.

**Comment by lstein** [comment]
That would be great. I don't actually have textual inversion set up on my system - support was contributed by a different developer. You might try going back to the September 8 commit 33874bae8db71dcdb5525826a1ec93b105e841ad. This is just before we started adding a lot of optimization code. If still broken, try September 5 720e5cd6513cd27e6d53feb6475dde20bd39841a, which is the previous commit that might have touched something in the training code.

**Comment by thelamedia** [comment]
I'll try both of these commits and report back.

**Comment by xiohexia** [comment]
I was having this issue and undoing this commit fixed this issue for me:
https://github.com/lstein/stable-diffusion/commit/62863ac586194a43ff952eba17a83cecf9956500

**Comment by lstein** [comment]
Thanks for the heads up. I've also reproduced the error and will now try to track it down.

**Comment by trathpai** [comment]
Its happening on Linux as well. Removing the mentioned PR solves the issue.

**Comment by CodeExplode** [comment]
I ran into this issue error message today while making my own edits to the code. Torch doesn't mind a new copy of tensors being edited, but doesn't want you editing originals in certain situations. You can fix it by adding with torch.no_grad(): before the changes are made, but I don't know what the implications of it are.

**Comment by mh-dm** [comment]
Sorry about the breakage. Is there any guide to run a quick training flow so I can test PRs?

**Comment by lstein** [comment]
I've removed the PR to get things working in the release. If it can be added back using @torch.no_grad() or similar, that would be great.

Speaking of which, I need someone who has gotten textual inversion to work on this distribution to lead me through the steps you used to achieve success. I have tried following the recipe and am encountering horrendous issues including python process core dumps. I would like to get the problems isolated and fixed so that the process is stable. (Unfortunately the individual who contributed the code and documentation for TI support has moved on and is not available to help out.) 

I also note that there is an unanswered question in Discussions #460 from another user who is having issues with TI.

**Comment by CodeExplode** [comment]
I've been using a slightly older version of this repo for textual inversion.

The command to run it is something like this:

python main.py --base ./configs/stable-diffusion/v1-finetune.yaml -t --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt -n project_name --gpus 0, --data_root ./training_data/pics/

v1-finetune.yaml will need to be edited with an initializer_words (which needs to map to one vector, some words map to two, though the code can fairly easily be changed to allow initializer words which map to multiple tokens, which I outlined the steps for here https://github.com/rinongal/textual_inversion/issues/65 ). The initializer_word should be as close as you can get to your current subject using existing prompts, because the vector which the word maps to will then be trained towards producing your training object (e.g. 'man' might be a good initializer word if trying to build an embeddable token for a person, and a similar looking celebrity might even be better).

The num_vectors_per_token field can also be raised to a higher number, making the token more like a sentence rather than one word, which can help capture more complex ideas. Stable Diffusion caps out at something like 77 input vectors, and using a token with a higher number of vectors can have an overwhelming effect on all the other prompts, so it's trickier to use, but more capable.

v1-inference.yaml will also need num_vectors_per_token inceased to test with an embedding file with more than one vector. That being said I think it can just be maxed out at 77 because the embedding manager code will only use up to an embedding's vector count.

The prompts used for generating test images in personalized.py, in the imagenet_templates_small set, should probably be changed to match the type of item you're training on, and maybe also be tuned to your training data images, describing features you don't want the embedding to capture (e.g. 'a picture of {} on a blue background', so that all the test images will generate with blue backgrounds and hopefully not train the embedding on that - or against the absence of that - if your training data all has blue backgrounds). It's unclear if this works. Some people have suggested just replacing all the tests with a single '{}' works better.

I'm unsure how to test embeddings from the command line but have been using the GUI versions to do that. Generally you'd use them like "a picture of *", or "a picture of embedding_file_name" if you have a branch where embedding file names can be used instead of tokens.

The batch count and num workers can be reduced to 1 and 2 in v1-finetune.yaml to bring the the vram requirements down to about 11gb. Theoretically adding something like accumulate_grad_batches: 4 in the trainer section down the bottom should help, but it seems to cause bugs in the testing process where it won't run tests until 4 times as many steps, and then runs them 4 times in a row, (which goes back to the original branch I think).

Dramatically increasing max_steps at the bottom of v1-finetune.yaml is probably a good idea. After stopping it manually, checking various checkpoints can help find if it overtrained and if there's an ideal embedding to use.

**Comment by CodeExplode** [comment]
I should also mention that training images should all be 512x512, though there are some lines you can change in finetune.yaml to train on 256x256 images, which may be faster.

In the training images output folder, you will files called:

input_gs - the original image
reconstruction_gs - the image after it has been compressed into SD's input format, and then uncompressed again, which is useful to see if fine details are being particularly messed up in your training data before even making it to the next stage, where you might need closer/different shots to get around that (I've been told on discord that it compresses down to 64x64 and then is upscaled using AI)
samples_gs - I think this is your test prompt generated with a CFG weight of 1, should mostly be gibberish
samples_scaled_gs - your test prompt generated with CFG 5 I think (or maybe the default 7.5), should be getting better over time.

**Comment by mh-dm** [comment]
Thank you. Based on your replies and https://github.com/lstein/stable-diffusion/blob/main/docs/features/TEXTUAL_INVERSION.md I've managed to repro the error reported that happens when (re)applying 62863ac but only with local changes. My card is only 8gb so I get OOMs with cuda in the training flow - the memory optimizations to attention.py are not enough/don't work with training. Instead I went the route of running on CPU only which is too slow to do anything except validate 1 epoch (of 3 repeats) then abort, i.e. no useful output of textual inversion.
But at least I have a repro so I can find a way to re-land 62863ac
