### ISSUE TITLE
Variations are not working via cli or web api

### ISSUE THREAD

**Issue by ausbitbank** [lstein/stable-diffusion#562]
**Describe your environment**
- GPU: nvidia 1080ti cuda
- VRAM: 11gb
- CPU arch: x86
- OS: Windows 10
- Python: Anaconda python 3.8.5
- Branch: tried both main and development
- Commit: 89da371f4841f7e05da5a1672459d700c3920784 (HEAD -> main, origin/main, origin/HEAD)

**Variations not working**
I'm unable to get the variations feature to affect output in any measurable way either via cli or web api. I've tried on both main and dev branches, using example commands from documentation and other github issues discussing the feature. I'm not sure when it broke, but it feels pretty broken now

**To Reproduce**

In cli run the command `anonymous -n3 -v0.01`

It's the same if I specify a seed `anonymous -n3 -v0.01 -S42`

Same result if I also add in other seeds and weights with -V eg : `anonymous -n3 -v0.01 -S42 -V42:1`

**Expected behavior**
From the documentation I would have expected to get 3 very similar copies of an image with slight variations. All are completely different.

**Comment by lstein** [comment]
I'm afraid I cannot confirm this, although I checked only on the development branch. You need to realize that you do have to supply a seed with -S in order to "center" the variations, so the usual workflow is to use -nX to generate a bunch of images the usual way, select one that you like, and request variations using seed X.

To illustrate, here is the original image from which I selected the seed (apologies for the ugly image, I just chose the first that came up):
![000235 1950357039](https://user-images.githubusercontent.com/111189/190142878-21b9c7b5-12bd-457a-8643-a8d513df6d98.png)

And here here are three variations generated with **portrait of a lovely lady -v0.1 -n3 -S1950357**:

![000236 1021076003](https://user-images.githubusercontent.com/111189/190141402-4fcbda63-3120-4b5a-b190-a9fd52b1fd66.png)
![000236 1226070308](https://user-images.githubusercontent.com/111189/190141403-61907c6e-dd07-488f-a563-931a188e15d6.png)
![000236 3870783890](https://user-images.githubusercontent.com/111189/190141404-dc3644a9-33ec-4826-8e95-0f07bb4ef445.png)

Here are three variations generated with **-v0.01**. As expected, the variations are more subtle than the first group:

![000237 1745389862](https://user-images.githubusercontent.com/111189/190141677-94ba1a1f-ab32-47c9-b33d-5ffee487be6a.png)
![000237 2840131136](https://user-images.githubusercontent.com/111189/190141678-745bc9a5-37de-4ba8-be5f-8df3a2f59718.png)
![000237 4040422332](https://user-images.githubusercontent.com/111189/190141681-151882b9-7064-4d69-8031-e2a21b5855da.png)

Are you using the default (klms) sampler? Maybe you've found a bug affecting one of the other samplers.

**Comment by ausbitbank** [comment]
Good catch, I've been forcing the k_euler_a sampler on the command line maybe that's why

**Comment by ausbitbank** [comment]
It was the sampler. Using default k_lms it behaves as expected!
k_euler_a continues to be a wildcard...
Thanks for pointing towards sampler I hadn't made the connection at all :)
