### ISSUE TITLE
Omegaconf in main.py for textual inversion sending errors

### ISSUE THREAD

**Issue by Bored-Anarchist** [lstein/stable-diffusion#651]
**Describe the bug**

When running main.py with recommended values and commands and the backend set to gloo, OmegaConf sends errors while trying to run. 

```
python ./main.py --base ./configs/stable-diffusion/v1-finetune.yaml \ 
-t true \
 --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt \   
-n my_cat \ 
--gpus 0, \
--data_root ./training_data/cat/ 
```
```
Global seed set to 23
Traceback (most recent call last):
  File "./main.py", line 691, in <module>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "./main.py", line 691, in <listcomp>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "C:\Users\x\.conda\envs\ldm\lib\site-packages\omegaconf\omegaconf.py", line 183, in load
with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\'
```
Any ideas on what I am missing? Thanks.

**Comment by lstein** [comment]
I don't see anything wrong with either the code or how you are calling it. It might help to put a debugging statements in front of and after line 691, like so:

~~~
print(f'opt.base = {opt.base}')                     <== new
configs = [OmegaConf.load(cfg) for cfg in opt.base]
print(f'configs = {configs}')                          <== new
~~~

Can I assume you haven't edited configs/stable-diccusion/v1-finetune.yaml?
Another thing to try is to use the windows backslashes for the --base filename instead of the Linux/Max style forward slashes. It isn't supposed to be necessary, but it can't hurt to try.

**Comment by Bored-Anarchist** [comment]
I added the recommended debugging statements and received this statement.
```
opt.base = ['.\\configs\\stable-diffusion\\v1-finetune.yaml', '\\']
```
The only modification I made to finetune.yaml was to add the init_word directly instead of in the prompt. I also tested the backslashes instead of the forward slashes, but there was no change.

**Comment by lstein** [comment]
Ah. There's an unwanted second element to the array, the '\\'. Where could that be coming from? Could you try removing the space at the end of the very first line of the command, so that it looks like:

~~~~
python ./main.py --base ./configs/stable-diffusion/v1-finetune.yaml \
-t true \
 --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt \
-n my_cat \
--gpus 0, \
--data_root ./training_data/cat/
~~~~

I don't know if cut-and-paste from the terminal, but there are extra spaces after the backslashes at the ends of some of your lines, and this could be confusing the command line parser.

**Comment by Bored-Anarchist** [comment]
That solved the issue, thanks. But now a new one has popped up, so I will open a new issue now.
