### ISSUE TITLE
Is it possible to encode existing (non-generated) images into the latent space and interpolate between them?

### ISSUE THREAD

**Issue by lendrick** [lstein/stable-diffusion#80]
Apologies if this isn't technically feasible, but would it be possible to specify two images (from an external source, containing no generation metadata), encode them into the latent space, and interpolate between them?

**Comment by Oceanswave** [comment]
Huh. That would be a super trippy way to do a morph. Interesting

**Comment by morganavr** [comment]
This would be a fantastic feature because then we could apply Prompt Weighting ( https://github.com/lstein/stable-diffusion/pull/18 ) to change image slightly. For example, you have a picture of a woman without a hat. Then you add "had:0.2" to the prompt and magically she wears a hat. Possibilities would be endless!

Naïve me tried to get this feature by using img2img module with "woman standing on a street" prompt and --strength = 0.01 to get a new generated image that looked the same as original with a goal to get a Seed. 

Then I used regular txt2img module with the same prompt and Seed hoping that it would create the exact same image but it did not work.

**Comment by lstein** [comment]
You can almost do this now using the img2img feature. You need to have a starting image that is exactly the size of the desired destination (you can use one already generated by SD) and pass this in using the -I switch:

dream> "woman with hat" -I./woman_without_a_hat.png

Here's an example of changing a cat into a tiger.
![000019 2696931809](https://user-images.githubusercontent.com/111189/186683866-05e38045-d649-4ebd-8db9-baaa2912997c.png)
![000020 1739352435](https://user-images.githubusercontent.com/111189/186683887-b158d2e4-06c7-4751-8ab4-d6cb3008eb6c.png)

**Comment by morganavr** [comment]
> You can almost do this now using the img2img feature. You need to have a starting image

With img2img user is forced to provide a base image,  prompt  and strength parameters to generate  a similarly looking image of various degree depending on strength value. 

This feature on the other hand works very differently. First you provide a base image, then SD does some magic and finds in its latent space almost exactly the same image and returns you a Seed to it (like a key). Then you can share with other people just a text prompt with a seed and they could see that image.

Maybe you can consider reopening this issue? It is a very interesting and challenging task and maybe somebody could crack it.
