### ISSUE TITLE
Allow dream.py to poll a file for prompts

### ISSUE THREAD

**Issue by Cubox** [lstein/stable-diffusion#93]
Hi

A feature I would love would be the ability to keep dream open, and feed it through another process prompts, so it can run them when needed.
My aim is to make a discord bot, where the bot would give dream.py the prompt.
I'm not sure this can simply be done using stdin, and I would rather start the dream.py script manually rather then have the bot start it.
If this is implemented, a way to get as an output only the generated image path would be excellent for the discord bot

**Comment by lstein** [comment]
If you are on a linux or mac system, you can make dream.py read from standard input by passing "/dev/stdin" as the argument to --from_file, i.e.
~~~~
python scripts/dream.py --from_file=/dev/stdin
~~~~
You can do this as part of a pipeline:
~~~~
echo "I dream of a genie with light brown hair" | python scripts/dream.py --from_file=/dev/stdin
~~~~
This won't work on Windows, but I will jigger the script a bit so that passing "-" as the file path argument will open standard input on either Windows or Linux. This betrays my background as a Perl hacker.

However, a simple pipe may not work for you, and possibly you may need to create a named pipe. This will give you a file-like endpoint that you write to, which is attached in turn to another file-like endpoint that dream.py reads from. This is a Linux thing, but if you are on such a system there's an old but good introduction here: https://www.linuxjournal.com/article/2156 . If you need bidirectional communication you can create another named pipe that works in the opposite direction, and just redirect dream.py's standard output to it using the redirection operator (>).

I have no idea how you do this in Windows.

Let me know more about your bot requirements and I will try to help.

**Comment by Cubox** [comment]
Thanks for the really detailed reply,

I didn't think --from-file would work with /dev/stdin, or a fifo pipe for that matter.
I will try it in a terminal with fifo pipes for stdin and stdout, and if this works, I'll make the bot using them.

I assume the --from_file input is reasonably safe to let people use (in a private server) without any major security issue, but let me know if there is a potential risk with it.

If the bot is a success, and if you are interested, I will gladly share its code, so it can be added to this repo.

**Comment by Cubox** [comment]
Unfortunately, since you detect the end of the input file here https://github.com/lstein/stable-diffusion/blob/4f02b72c9ca464f53c0f7f23ee483f7a24b631ad/scripts/dream.py#L140
I would have to keep the file open, or have the code modified to keep listening
