### ISSUE TITLE
Feature request: prompt2image option to output intermediate images

### ISSUE THREAD

**Issue by TesseractCat** [lstein/stable-diffusion#99]
It would be cool if there was a way to see the intermediate results as the sampler creates the image. This could be useful for samplers such as `k_euler_a` which varies quite a bit between steps, as a way to generate variations.

Perhaps the `prompt2image` function could have an `intermediates` parameter, which would be an array of steps to save images at.

So for example, one could call `prompt2image("astronaut riding a horse", steps = 50, intermediates = [10, 20, 30, 40])`.

Here is an example of an intermediate images using the `k_euler_a` sampler at steps 30, 25, 20, and 15:

![image](https://user-images.githubusercontent.com/16248379/186845310-90f01262-268a-454f-b86b-47a6eb271f17.png)

**Comment by TesseractCat** [comment]
Unfortunately, I think that would regenerate the image for each increase in step value. This means that for my example you would cumulatively evaluate 10 + 20 + 30 + 40 + 50 = 150 steps.

**Comment by TesseractCat** [comment]
The problem with that command is that it would end up generating the image 5 times, just with different step values. This PR is asking for a way to save intermediate results as an image is being generated. This would be a lot faster as you would only have to generate an image once to get the intermediate results.

**Comment by TesseractCat** [comment]
Well, the interpolation is a feature of the `dream.py` script. I'm asking for a lower-level interface through the simplet2i class (most likely what the interpolation would build upon if it added that special case).

**Comment by morganavr** [comment]
> So for example, one could call prompt2image("astronaut riding a horse", steps = 50, intermediates = [10, 20, 30, 40]).

I would like to see **all** intermediate images while final image is generating and specifying each image # in `--intermediates` parameter is too time consuming.

What if `all` value could be passed to `--intermediates` making it generate all the intermediate images?
> prompt2image("astronaut riding a horse", steps=50, intermediates = ["all"]).

**Comment by bakkot** [comment]
The [`sample`](https://github.com/lstein/stable-diffusion/blob/b0b4ccf5212b6d129b0907bf2e0a2d170f2ca0f6/ldm/models/diffusion/ddim.py#L117) method which underlies `txt2img` actually already takes a `img_callback` parameter which gets invoked at each step. All that's necessary is to provide a callback for that parameter at [the callsite](https://github.com/lstein/stable-diffusion/blob/b0b4ccf5212b6d129b0907bf2e0a2d170f2ca0f6/ldm/simplet2i.py#L365-L374) (at least for `txt2img`; making it work for `img2img` would require tweaking the [`decode`](https://github.com/lstein/stable-diffusion/blob/b0b4ccf5212b6d129b0907bf2e0a2d170f2ca0f6/ldm/models/diffusion/ddim.py#L373) method to support such a parameter as well).

As a matter of a design, I think a callback which takes the image and index and is called at each iteration is cleanest. That way you can choose to only save every item or every 10th item or whatever you want.

I think it would be cool to integrate this with the web UI too so that the final image would slowly come into focus.

**Comment by green-s** [comment]
I've been using the img_callback to do this in my own Streamlit-based web UI. Works fine with DDIM and PLMS but not with k_lms (and most likely the other k-diffusion samplers, haven't implemented support for those). k_lms doesn't seem to trigger it, except maybe after completion, haven't checked since I update the image at the end anyway.

**Comment by BlueAmulet** [comment]
It's also worth noticing that although k_euler_a has wildly different outputs depending on the number of steps, it doesn't actually look like that in it's intermediates. You're going to just see a blurrier fuzzier version of the final image.

The k-diffusion samplers do have a callback but it isn't implemented in the wrapper and isn't directly compatible with the ddim and plms sampler callbacks.

<details>
<summary>Intermediate examples</summary>

Step 34
![33 0 dni](https://user-images.githubusercontent.com/43395286/187005203-e9ed8904-62eb-4374-b398-fc51659653ec.png)
Step 67
![66 0 dni](https://user-images.githubusercontent.com/43395286/187005214-a1cd9402-84b1-4a71-9d40-67dfababe3cd.png)
Step 100
![99 0 dni](https://user-images.githubusercontent.com/43395286/187005218-6e1a7ba9-cffc-4063-b1f1-854462ef18f2.png)
</details>
